### ISSUE TITLE
数据库连接池创建失败，提示Datasource[name=dao, Driver=null] created.

### ISSUE THREAD

**Issue by hanyi366** [ctripcorp/dal#23]
首次安装后，提示连接失败，查看日志提示Unable to create initial connections of pool.
Datasource[name=dao, Driver=null] created.

但是数据库配置文件是没错的
`<Datasource name="dao" userName="root" password="123456" connectionUrl="jdbc:mysql://127.0.0.1:3306/CodeGen" driverClassName="com.mysql.jdbc.Driver"/>`

**Comment by wangyenan** [comment]
能否贴一下相关的堆栈信息，还有，JDK版本，Tomcat版本是多少？

**Comment by hejiehui** [comment]
你是哪个版本的dal-client?要不你到qq群307228594里面来，我们帮你看看

**Comment by hanyi366** [comment]
jdk1.7 tomcat7 与 jdk1.8 tomcat8 都测试过，不行

`[ INFO][12-20 20:05:56.900][http-bio-8080-exec-1][DAL Java Client 1.14.0:74]-Successfully initialized Dal Java Client Factory
[ INFO][12-20 20:05:57.010][http-bio-8080-exec-1][DAL Java Client 1.14.0:197]-start request
[ INFO][12-20 20:05:57.012][http-bio-8080-exec-1][DAL Java Client 1.14.0:31]-Start Task: N/A
[ INFO][12-20 20:05:57.017][http-bio-8080-exec-1][com.ctrip.platform.dal.dao.datasource.SingleDataSource:51]-Datasource[name=dao, Driver=null] created.
[ INFO][12-20 20:05:57.112][http-bio-8080-exec-1][com.ctrip.platform.dal.dao.datasource.SingleDataSource:56]-Datasource[name=dao, Driver=null] created.
Dec 20, 2017 8:05:57 PM org.apache.tomcat.jdbc.pool.ConnectionPool init
严重: Unable to create initial connections of pool.
java.sql.SQLException
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:254)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:727)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:661)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:479)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:156)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:116)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:103)
	at com.ctrip.platform.dal.dao.datasource.SingleDataSource.<init>(SingleDataSource.java:57)
	at com.ctrip.platform.dal.dao.datasource.RefreshableDataSource.<init>(RefreshableDataSource.java:19)
	at com.ctrip.platform.dal.dao.datasource.DataSourceLocator.createDataSource(DataSourceLocator.java:73)
	at com.ctrip.platform.dal.dao.datasource.DataSourceLocator.getDataSource(DataSourceLocator.java:56)
	at com.ctrip.platform.dal.dao.datasource.DefaultDalConnectionLocator.getConnection(DefaultDalConnectionLocator.java:36)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager.getConnectionFromDSLocator(DalConnectionManager.java:120)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager.getNewConnection(DalConnectionManager.java:54)
	at com.ctrip.platform.dal.dao.client.DalTransactionManager.getConnection(DalTransactionManager.java:112)
	at com.ctrip.platform.dal.dao.client.DalTransactionManager.getConnection(DalTransactionManager.java:87)
	at com.ctrip.platform.dal.dao.client.DalDirectClient.getConnection(DalDirectClient.java:425)
	at com.ctrip.platform.dal.dao.client.DalDirectClient$1.execute(DalDirectClient.java:55)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager._doInConnection(DalConnectionManager.java:157)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager.doInConnection(DalConnectionManager.java:134)
	at com.ctrip.platform.dal.dao.client.DalDirectClient.doInConnection(DalDirectClient.java:413)
	at com.ctrip.platform.dal.dao.client.DalDirectClient.query(DalDirectClient.java:76)
	at com.ctrip.platform.dal.dao.task.QuerySqlTask.execute(QuerySqlTask.java:19)
	at com.ctrip.platform.dal.dao.task.DalSqlTaskRequest$SqlTaskCallable.call(DalSqlTaskRequest.java:170)
	at com.ctrip.platform.dal.dao.task.RequestTaskWrapper.call(RequestTaskWrapper.java:33)
	at com.ctrip.platform.dal.dao.task.DalRequestExecutor.nonCrossShardExecute(DalRequestExecutor.java:133)
	at com.ctrip.platform.dal.dao.task.DalRequestExecutor.internalExecute(DalRequestExecutor.java:113)
	at com.ctrip.platform.dal.dao.task.DalRequestExecutor.execute(DalRequestExecutor.java:98)
	at com.ctrip.platform.dal.dao.DalQueryDao.query(DalQueryDao.java:132)
	at com.ctrip.platform.dal.daogen.dao.DaoOfLoginUser.getUserByNo(DaoOfLoginUser.java:46)
	at com.ctrip.platform.dal.daogen.entity.DefaultUserInfo.getLoginUser(DefaultUserInfo.java:23)
	at com.ctrip.platform.dal.daogen.entity.DefaultUserInfo.getEmployee(DefaultUserInfo.java:29)
	at com.ctrip.platform.dal.daogen.resource.CustomizedResource.getEmployee(CustomizedResource.java:82)
	at com.ctrip.platform.dal.daogen.filter.UserFilter.doFilter(UserFilter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:246)
	... 51 more

[ERROR][12-20 20:05:57.143][http-bio-8080-exec-1][com.ctrip.platform.dal.dao.datasource.SingleDataSource:60]-Error creating pool for data source dao
java.sql.SQLException: null
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:254)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:727)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:661)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:479)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:156)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:116)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:103)
	at com.ctrip.platform.dal.dao.datasource.SingleDataSource.<init>(SingleDataSource.java:57)
	at com.ctrip.platform.dal.dao.datasource.RefreshableDataSource.<init>(RefreshableDataSource.java:19)
	at com.ctrip.platform.dal.dao.datasource.DataSourceLocator.createDataSource(DataSourceLocator.java:73)
	at com.ctrip.platform.dal.dao.datasource.DataSourceLocator.getDataSource(DataSourceLocator.java:56)
	at com.ctrip.platform.dal.dao.datasource.DefaultDalConnectionLocator.getConnection(DefaultDalConnectionLocator.java:36)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager.getConnectionFromDSLocator(DalConnectionManager.java:120)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager.getNewConnection(DalConnectionManager.java:54)
	at com.ctrip.platform.dal.dao.client.DalTransactionManager.getConnection(DalTransactionManager.java:112)
	at com.ctrip.platform.dal.dao.client.DalTransactionManager.getConnection(DalTransactionManager.java:87)
	at com.ctrip.platform.dal.dao.client.DalDirectClient.getConnection(DalDirectClient.java:425)
	at com.ctrip.platform.dal.dao.client.DalDirectClient$1.execute(DalDirectClient.java:55)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager._doInConnection(DalConnectionManager.java:157)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager.doInConnection(DalConnectionManager.java:134)
	at com.ctrip.platform.dal.dao.client.DalDirectClient.doInConnection(DalDirectClient.java:413)
	at com.ctrip.platform.dal.dao.client.DalDirectClient.query(DalDirectClient.java:76)
	at com.ctrip.platform.dal.dao.task.QuerySqlTask.execute(QuerySqlTask.java:19)
	at com.ctrip.platform.dal.dao.task.DalSqlTaskRequest$SqlTaskCallable.call(DalSqlTaskRequest.java:170)
	at com.ctrip.platform.dal.dao.task.RequestTaskWrapper.call(RequestTaskWrapper.java:33)
	at com.ctrip.platform.dal.dao.task.DalRequestExecutor.nonCrossShardExecute(DalRequestExecutor.java:133)
	at com.ctrip.platform.dal.dao.task.DalRequestExecutor.internalExecute(DalRequestExecutor.java:113)
	at com.ctrip.platform.dal.dao.task.DalRequestExecutor.execute(DalRequestExecutor.java:98)
	at com.ctrip.platform.dal.dao.DalQueryDao.query(DalQueryDao.java:132)
	at com.ctrip.platform.dal.daogen.dao.DaoOfLoginUser.getUserByNo(DaoOfLoginUser.java:46)
	at com.ctrip.platform.dal.daogen.entity.DefaultUserInfo.getLoginUser(DefaultUserInfo.java:23)
	at com.ctrip.platform.dal.daogen.entity.DefaultUserInfo.getEmployee(DefaultUserInfo.java:29)
	at com.ctrip.platform.dal.daogen.resource.CustomizedResource.getEmployee(CustomizedResource.java:82)
	at com.ctrip.platform.dal.daogen.filter.UserFilter.doFilter(UserFilter.java:30)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:962)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: null
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:246)
	... 51 common frames omitted
Dec 20, 2017 8:05:57 PM org.apache.tomcat.jdbc.pool.ConnectionPool init
严重: Unable to create initial connections of pool.`

**Comment by hejiehui** [comment]
这个是1.14.0的bug。没有对基于datasource.xml的数据库连接配置做支持。我们后面会发个1.14.1来fix这个issue。目前可以用外部properties文件的方式继续使用1.14.0或切换到1.13.x

**Comment by skilyxx** [comment]
您好，试了一下1.14.1还是有这个问题。
PoolProperties里参数是空的，导致了后面解析jdbc字符串的时候报错反射找不到mysql类。

信息: Server startup in 2786 ms
[ INFO][01-16 10:32:48.180][http-bio-8000-exec-1][com.ctrip.platform.dal.dao.configure.DataSourceConfigureParser:51]-datasource property will use file :/home/yeon/env/tomcat/apache-tomcat-7.0.61/webapps/ROOT/WEB-INF/classes/datasource.xml
[ INFO][01-16 10:32:48.186][http-bio-8000-exec-1][DAL Java Client 1.14.1:74]-Successfully initialized Dal Java Client Factory
[ INFO][01-16 10:32:48.209][http-bio-8000-exec-1][com.ctrip.platform.dal.dao.datasource.SingleDataSource:54]-pool properties: ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=null; maxActive=100; maxIdle=100; minIdle=0; initialSize=1; maxWait=10000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=30000; testWhileIdle=false; testOnConnect=false; password=********; url=null; username=null; validationQuery=SELECT 1; validationQueryTimeout=5; validatorClassName=com.ctrip.platform.dal.dao.datasource.DataSourceValidator; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=true; removeAbandonedTimeout=65; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=28000000; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; 
[ INFO][01-16 10:32:48.210][http-bio-8000-exec-1][com.ctrip.platform.dal.dao.datasource.SingleDataSource:57]-Prepare Datasource[name=dao, Driver=null]
一月 16, 2018 10:32:48 上午 org.apache.tomcat.jdbc.pool.ConnectionPool init
严重: Unable to create initial connections of pool.
java.sql.SQLException
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:254)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:727)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:661)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:479)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:156)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:116)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:103)
	at com.ctrip.platform.dal.dao.datasource.SingleDataSource.<init>(SingleDataSource.java:58)
	at com.ctrip.platform.dal.dao.datasource.RefreshableDataSource.<init>(RefreshableDataSource.java:22)
	at com.ctrip.platform.dal.dao.datasource.DataSourceLocator.createDataSource(DataSourceLocator.java:80)
	at com.ctrip.platform.dal.dao.datasource.DataSourceLocator.getDataSource(DataSourceLocator.java:59)
	at com.ctrip.platform.dal.dao.datasource.DefaultDalConnectionLocator.getConnection(DefaultDalConnectionLocator.java:38)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager.getConnectionFromDSLocator(DalConnectionManager.java:120)
	at com.ctrip.platform.dal.dao.client.DalConnectionManager.getNewConnection(DalConnectionManager.java:54)
	at com.ctrip.platform.dal.dao.client.DalTransactionManager.getConnection(DalTransactionManager.java:112)
	at com.ctrip.platform.dal.dao.client.DalTransactionManager.startTransaction(DalTransactionManager.java:34)
	at com.ctrip.platform.dal.dao.client.DalTransactionManager.doInTransaction(DalTransactionManager.java:150)
	at com.ctrip.platform.dal.dao.client.DalDirectClient.doInTransaction(DalDirectClient.java:418)
	at com.ctrip.platform.dal.dao.client.DalDirectClient.executeBatch(DalDirectClient.java:407)
	at com.ctrip.platform.dal.dao.client.DalDirectClient.batchUpdate(DalDirectClient.java:177)
	at com.ctrip.platform.dal.daogen.dao.SetupDBDao.executeSqlScript(SetupDBDao.java:25)
	at com.ctrip.platform.dal.daogen.resource.SetupDBResource.setupTables(SetupDBResource.java:376)
	at com.ctrip.platform.dal.daogen.resource.SetupDBResource.initializeDb(SetupDBResource.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.ctrip.platform.dal.daogen.filter.UserFilter.doFilter(UserFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:246)
	... 72 more

**Comment by skilyxx** [comment]
换了1.13.1，正常。

**Comment by wangyenan** [comment]
我们已经更新到最新的1.14.2版本，本地test case通过，你再试一下，如果仍旧不行，加我们的QQ群，我们帮你看一下是哪里的配置问题。

**Comment by ShawyerPeng** [comment]
我首先也出现这样的错误，然后加了mysql-connector-java包，就OK啦
