### ISSUE TITLE
DEMO无法建立数据库连接，使用的是dal-client:1.15.1版本

### ISSUE THREAD

**Issue by kiwigong** [ctripcorp/dal#33]
五月 30, 2018 1:46:32 下午 org.apache.tomcat.jdbc.pool.ConnectionPool init
严重: Unable to create initial connections of pool.
java.sql.SQLException
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:254)
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701)
	at com.ctrip.platform.dal.dao.datasource.tomcat.DalConnectionPool.createConnection(DalConnectionPool.java:27)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:486)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:144)
	at com.ctrip.platform.dal.dao.datasource.tomcat.DalConnectionPool.<init>(DalConnectionPool.java:20)

![3](https://user-images.githubusercontent.com/971585/40760249-783aa2de-64c8-11e8-8ceb-88a5d08be8a6.png)
![2](https://user-images.githubusercontent.com/971585/40760250-7871ebae-64c8-11e8-9e2a-7541718a09df.png)
![1](https://user-images.githubusercontent.com/971585/40760251-78a82d2c-64c8-11e8-9101-89f38862ffb6.png)

**Comment by DiaosX** [comment]
你可以这样改下试试：
`private DataSourceConfigure _getDataSourceConfigure(String name) {
        DataSourceConfigure configure = null;
        configure = dataSourceConfiguresCache.get(name);
        if (configure != null) {
            return configure;
        }
        ConnectionString connectionString = connectionStrings.get(name);
        if (connectionString == null) {
            configure = (DataSourceConfigure) this.getUserPoolPropertiesConfigure(name);
        } else {
            configure = mergeDataSourceConfigure(connectionString);
        }
        if (configure != null) {
            dataSourceConfiguresCache.put(name, configure);
        }
        return configure;
    }`

**Comment by wangyenan** [comment]
近期会修复这个问题，代码待合并。

**Comment by wangyenan** [comment]
master分支上的最新版已修复这个问题。
